language: python
python:
  - "2.7"
  # - "3.0" not available on Travis CI
  # - "3.1" not available on Travis CI
  # - "3.2" syntax error?
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python setup.py test